digitdata<-read.csv("pcaData/rawData.csv", sep=" ", header=FALSE)
library("lattice")
covdigit=cov(data.matrix(digitdata))
eigendigit=eigen(covdigit)
plot(eigendigit$values, ylab="eigenvalue", main="Eigenvalues of Covmat")

output=matrix(nrow=1934, ncol=64)
output=data.matrix(digitdata)%*%data.matrix(eigendigit$vectors[, c(1:64)])
write.table(output, file="pcaData/trainingData.csv", row.names=FALSE, col.names=FALSE, eol="\n")
write.table(eigendigit$vectors[, c(1:64)], file="pcaData/eigenvectors.csv", row.names=FALSE, col.names=FALSE, eol="\n")
